# Eocene creator configuration file
dirs:
  input: /lus/h2resw01/hpcperm/ccpd/ECE4-DATA-V2
  output: /lus/h2resw01/hpcperm/ccpd/EOCENE-TEST
  herold: /lus/h2resw01/hpcperm/ecme3497/herold-et-al-2014/Supp
  tmpdir: /lus/h2resw01/hpcperm/ccpd/eocene_tmp