# Create the eocene environment:
# mamba env create -f environment.yml 
# or 
# conda env create -f environment.yml

name : eocene
channels:
  - conda-forge
dependencies:
  - python>=3.9,<3.15
  - eccodes
  - cdo
  - xesmf
  - pip
  - pip:
    - -e .