hp_dict = {
    '1': 'tropical forest',
    '2': 'warm temperate forest',
    '3': 'temperate forest',
    '4': 'boreal forest',
    '5': 'savana',
    '6': 'grassland',
    '7': 'desert',
    '8': 'dry tundra',
    '9': 'tundra',
    '10': 'ice',
}

land_cover_types = {
    0: "No vegetation",
    1: "Crops, Mixed farming",
    2: "Grass",
    3: "Evergreen needleleaf trees",
    4: "Deciduous needleleaf trees",
    5: "Deciduous broadleaf trees",
    6: "Evergreen broadleaf trees",
    7: "Tall grass",
    8: "Desert",
    9: "Tundra",
    10: "Irrigated crops",
    11: "Semidesert",
    12: "Ice caps and Glaciers",
    13: "Bogs and marshes",
    14: "Inland water",
    15: "Ocean",
    16: "Evergreen shrubs",
    17: "Deciduous shrubs",
    18: "Mixed forest/woodland",
    19: "Interrupted forest",
    20: "Water and land mixtures"
}